// <auto-generated />
namespace TYUIU.PurginDS.LibraryManagementNetCoreWebAppMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddBorrowHistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBorrowHistory));
        
        string IMigrationMetadata.Id
        {
            get { return "202311151804421_Add Borrow History"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
